/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\项目文件\\Blog\\vuePress\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-c280b6e8",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c280b6e8").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-2503aa1c",
    path: "/firstside/child/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2503aa1c").then(next)
    },
  },
  {
    path: "/firstside/child/index.html",
    redirect: "/firstside/child/"
  },
  {
    name: "v-43e39b6e",
    path: "/firstside/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-43e39b6e").then(next)
    },
  },
  {
    path: "/firstside/index.html",
    redirect: "/firstside/"
  },
  {
    name: "v-5feb7c82",
    path: "/second/child/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5feb7c82").then(next)
    },
  },
  {
    path: "/second/child/index.html",
    redirect: "/second/child/"
  },
  {
    name: "v-36264d2c",
    path: "/firstside/otherModel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-36264d2c").then(next)
    },
  },
  {
    name: "v-7108e4ef",
    path: "/second/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7108e4ef").then(next)
    },
  },
  {
    path: "/second/index.html",
    redirect: "/second/"
  },
  {
    name: "v-d7d3273e",
    path: "/second/child/secondChild.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d7d3273e").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]