/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "不以by",
  "description": "你看起来很好吃",
  "base": "/vuepress/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/vuepress/assets/Yun.png"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/assets/avatar.png",
        "actionText": "快速上手 →",
        "actionLink": "/firstside/",
        "features": [
          {
            "title": "不务正业",
            "details": "对方向你发起美食共享，对方向你发起景色共享，对方向你发起游戏共享"
          },
          {
            "title": "一起摸鱼(划掉) 认真工作",
            "details": "我是一个认真工作的小宝贝"
          },
          {
            "title": "还没想好",
            "details": "等我想好再来"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-c280b6e8",
      "path": "/"
    },
    {
      "title": "我是child",
      "frontmatter": {},
      "regularPath": "/firstside/child/",
      "relativePath": "firstside/child/README.md",
      "key": "v-2503aa1c",
      "path": "/firstside/child/",
      "headers": [
        {
          "level": 2,
          "title": "二级第一个侧边栏",
          "slug": "二级第一个侧边栏"
        },
        {
          "level": 2,
          "title": "二级第二个侧边栏",
          "slug": "二级第二个侧边栏"
        },
        {
          "level": 3,
          "title": "三级第一个侧边栏",
          "slug": "三级第一个侧边栏"
        },
        {
          "level": 2,
          "title": "二级第三个侧边栏",
          "slug": "二级第三个侧边栏"
        }
      ]
    },
    {
      "title": "第一个侧边栏",
      "frontmatter": {},
      "regularPath": "/firstside/",
      "relativePath": "firstside/README.md",
      "key": "v-43e39b6e",
      "path": "/firstside/",
      "headers": [
        {
          "level": 2,
          "title": "二级第一个侧边栏",
          "slug": "二级第一个侧边栏"
        },
        {
          "level": 2,
          "title": "二级第二个侧边栏",
          "slug": "二级第二个侧边栏"
        },
        {
          "level": 3,
          "title": "三级第一个侧边栏",
          "slug": "三级第一个侧边栏"
        },
        {
          "level": 2,
          "title": "二级第三个侧边栏",
          "slug": "二级第三个侧边栏"
        }
      ]
    },
    {
      "title": "我是第二个侧边栏",
      "frontmatter": {},
      "regularPath": "/second/child/",
      "relativePath": "second/child/README.md",
      "key": "v-5feb7c82",
      "path": "/second/child/"
    },
    {
      "title": "我是其他模块的",
      "frontmatter": {},
      "regularPath": "/firstside/otherModel.html",
      "relativePath": "firstside/otherModel.md",
      "key": "v-36264d2c",
      "path": "/firstside/otherModel.html"
    },
    {
      "title": "我是第二个侧边栏",
      "frontmatter": {},
      "regularPath": "/second/",
      "relativePath": "second/README.md",
      "key": "v-7108e4ef",
      "path": "/second/"
    },
    {
      "title": "我是第二个侧边栏的子元素",
      "frontmatter": {},
      "regularPath": "/second/child/secondChild.html",
      "relativePath": "second/child/secondChild.md",
      "key": "v-d7d3273e",
      "path": "/second/child/secondChild.html"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "其他文档",
        "items": [
          {
            "text": "demo1",
            "link": "http://www.baidu.com"
          },
          {
            "text": "demo2",
            "link": "http://www.baidu.cn"
          }
        ]
      }
    ],
    "sidebarDepth": 4,
    "sidebar": [
      {
        "title": "第一个侧边栏",
        "collapsable": false,
        "children": [
          "/firstside/",
          "/firstside/otherModel",
          "/firstside/child/"
        ]
      },
      {
        "title": "第二个侧边栏",
        "collapsable": true,
        "children": [
          "/second/",
          {
            "title": "侧边栏组合",
            "collapsable": true,
            "children": [
              "/second/child/",
              "/second/child/secondChild"
            ]
          }
        ]
      }
    ]
  }
}